<a href="https://colab.research.google.com/github/amazingashis/Machine_Learning_Advanced/blob/main/2_Introduction_to_Tensor_Flow_2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to Tensorflow**

<img src = "https://camo.githubusercontent.com/127d2d82f76ed9d98414011fd743b58e7c094ce4/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f313032352f312a7657734978594733456b5237435f6c737a69715046512e706e67"/>

# **What is Tensor?**
A tensor is an N-dimensional array of data

<img src = "https://camo.githubusercontent.com/7b892ce75089d13d7a55a9e3ba037171cd9a1e99/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d68757a616966616465762f6d6c5f7a65726f5f746f5f6865726f2f6d61737465722f74656e736f722e706e673f746f6b656e3d414d534753515a445a5a4f4732484e4c4b4d5837534753373258345134"/>


# **Components of TensorFlow: Tensors and Variables**



In [1]:
import tensorflow as tf

print(tf.__version__)

2.3.0


In [2]:
import numpy as np
print(np.__version__)

1.18.5


In [4]:
x = tf.constant([[3,5,7],[4,6,8]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 7],
       [4, 6, 8]], dtype=int32)>

In [5]:
y = x[:,1]
y

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>

In [6]:
y = tf.reshape(x,[3,2])
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [7, 4],
       [6, 8]], dtype=int32)>

In [7]:
#Here is a "scalar" or "rank-0" tensor . A scalar contains a single value, and no "axes".
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
rank_1_tensor = tf.constant([2.0,3.0,4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [9]:
rank_2_sensor = tf.constant([[1,2],[3,4],[5,6]])
print(rank_2_sensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


<img src = "https://camo.githubusercontent.com/a27c59b02b8c3aa85b1b48b2c35af7500ad2660c/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d68757a616966616465762f6d6c5f7a65726f5f746f5f6865726f2f6d61737465722f74656e732e706e673f746f6b656e3d414d53475351334633374d554b56324f535a5957354c32373259424749"/>

In [10]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
                    
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


<img src = "https://camo.githubusercontent.com/41417d186a7bbd3587f5992e1163c0eeb4290efe/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d68757a616966616465762f6d6c5f7a65726f5f746f5f6865726f2f6d61737465722f336178697374656e736f722e706e673f746f6b656e3d414d5347535137575958575754485a4c5a364841324e53373259425232"/>

**you can convert a tensor to a NumPy array either using np.array or the tensor.numpy method:**

In [11]:
np.array(rank_2_sensor)

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [12]:
rank_2_sensor.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>>

**We can do basic math on tensors, including addition, element-wise multiplication, and matrix multiplication**

In [13]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a,b),"\n")

print(tf.multiply(a,b),"\n")

print(tf.matmul(a,b),"\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [14]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



**Tensors are used in all kinds of operations (ops).**

In [15]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

#Find the largest values
print(tf.reduce_max(c))

#Find the index of largest value

print(tf.math.argmax(c))

#Compute the Softmax
tf.nn.softmax(c)

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105860e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>


# **About Shapes**
Tensors have shapes. Some vocabulary:


* Shape: The length (number of elements) of each of the dimensions of a tensor.
* Rank: Number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
* Axis or Dimension: A particular dimension of a tensor.
* Size: The total number of items in the tensor, the product shape vector


Note: Although you may see reference to a "tensor of two dimensions", a rank-2 tensor does not usually describe a 2D space.

Tensors and tf.TensorShape objects have convenient properties for accessing these:



In [16]:
rank_4_tensor = tf.zeros([3,2,4,5])
rank_4_tensor

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

<img src = "https://camo.githubusercontent.com/55636e7c182680afc3decf7bc69470c6f84a19c3/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d68757a616966616465762f6d6c5f7a65726f5f746f5f6865726f2f6d61737465722f7368617065732e706e673f746f6b656e3d414d53475351364a4a504d594233354f484c3643324632373259454347"/>


In [18]:
print("Type of every elements :",rank_4_tensor.dtype)
print("Number of Dimensions :", rank_4_tensor.ndim)
print("shape of tensor :", rank_4_tensor.shape)
print("Elements along x axis 0 of tensor :",rank_4_tensor.shape[0])
print("Elements along last of tensor :",rank_4_tensor.shape[1])
print("Total No of Elements (3*2*4*5) :",tf.size(rank_4_tensor).numpy())

Type of every elements : <dtype: 'float32'>
Number of Dimensions : 4
shape of tensor : (3, 2, 4, 5)
Elements along x axis 0 of tensor : 3
Elements along last of tensor : 2
Total No of Elements (3*2*4*5) : 120


While axes are often referred to by their indices, you should always keep track of the meaning of each. Often axes are ordered from global to local: The batch axis first, followed by spatial dimensions, and features for each location last. This way feature vectors are contiguous regions of memory.

<img src = "https://camo.githubusercontent.com/eac2b4c2eb4f0b900964169c2a3be284c3f47ac9/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d68757a616966616465762f6d6c5f7a65726f5f746f5f6865726f2f6d61737465722f72616e6b342e706e673f746f6b656e3d414d534753513650595446554a55514f3656494f324f4b373259455232"/>


# **Single-axis indexing**
TensorFlow follow standard python indexing rules, similar to indexing a list or a string in python, and the bacic rules for numpy indexing.

indexes start at 0 negative indices count backwards from the end colons, :, are used for slices start:stop:step


In [19]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())


[ 0  1  1  2  3  5  8 13 21 34]


**Indexing with a scalar removes the dimension:**

In [20]:

print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

First: 0
Second: 1
Last: 34


**Indexing with a : slice keeps the dimension:**

In [21]:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


 **Multi-axis indexing**
 
Higher rank tensors are indexed by passing multiple indices.

The single-axis exact same rules as in the single-axis case apply to each axis independently.

In [23]:
print(rank_2_sensor.numpy())

[[1 2]
 [3 4]
 [5 6]]


**Passing an integer for each index the result is a scalar.**

In [25]:
# Pull out a single value from a 2-rank tensor
print(rank_2_sensor[1, 1].numpy())

4


**You can index using any combination integers and slices:**

In [29]:

# Get row and column tensors
print("Second row:", rank_2_sensor[1, :].numpy())
print("Second column:", rank_2_sensor[:, 1].numpy())
print("Last row:", rank_2_sensor[-1, :].numpy())
print("First item in last column:", rank_2_sensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_sensor[1:, :].numpy(), "\n")

Second row: [3 4]
Second column: [2 4 6]
Last row: [5 6]
First item in last column: 2
Skip the first row:
[[3 4]
 [5 6]] 



Here is an example with a 3-axis tensor:

In [28]:
print(rank_3_tensor[:, :, 4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


<img src ="https://camo.githubusercontent.com/7eb314ab83ec0e9716d93e2233181e0a3ab0346d/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d68757a616966616465762f6d6c5f7a65726f5f746f5f6865726f2f6d61737465722f72616e6b332e706e673f746f6b656e3d414d53475351354f59574c4a335541324d515541514343373259464c4f"/>


# **Manipulating Shapes**
Reshaping a tensor is of great utility.

The tf.reshape operation is fast and cheap as the underlying data does not need to be duplicated.

In [30]:
# Shape returns a `TensorShape` object that shows the size on each dimension
var_x = tf.Variable(tf.constant([[1], [2], [3]]))
print(var_x.shape)

(3, 1)


In [31]:
# You can convert this object into a Python list, too
print(var_x.shape.as_list())

[3, 1]


In [32]:
# We can reshape a tensor to a new shape.
# Note that we're passing in a list
reshaped = tf.reshape(
    var_x, [1,3]
)

In [33]:
print(var_x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


In [34]:
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


If you flatten a tensor you can see what order it is laid out in memory.

In [35]:
print(tf.reshape(rank_3_tensor, [-1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


Typically the only reasonable uses of tf.reshape are to combine or split adjacent axes (or add/remove 1s).

For this 3x2x5 tensor, reshaping to (3x2)x5 or 3x(2x5) are both reasonable things to do, as the slices do not mix:

In [41]:
print(tf.reshape(rank_3_tensor, [3*2, 5]), "\n")
print(tf.reshape(rank_3_tensor, [3, -1]))
print(tf.reshape(rank_3_tensor, [2,-1]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)
tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]], shape=(2, 15), dtype=int32)


<img src = "https://camo.githubusercontent.com/cfca6ee2d723cdb445ab1691af20bf801b6311a9/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d68757a616966616465762f6d6c5f7a65726f5f746f5f6865726f2f6d61737465722f636f6e63657074732e706e673f746f6b656e3d414d53475351375832355a5647515942584e52344a3732373259475745"/>

Reshaping will "work" for any new shape with the same total number of elements, but it will not do anything useful if you do not respect the order of the axes.

Swapping axes in tf.reshape does not work, you need tf.transpose for that.



# **Broadcasting**
Broadcasting is a concept borrowed from the equivalent feature in NumPy. In short, under certain conditions, smaller tensors are "stretched" automatically to fit larger tensors when running combined operations on them.

The simplest and most common case is when you attempt to multiply or add a tensor to a scalar. In that case, the scalar is broadcast to be the same shape as the other argument.

In [42]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])
# All of these are the same computation
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


Likewise, 1-sized dimensions can be stretched out to match the other arguments. Both arguments can be stretched in the same computation.

In this case a 3x1 matrix is element-wise multiplied by a 1x4 matrix to produce a 3x4 matrix. Note how the leading 1 is optional: The shape of y is [4].

In [43]:

# These are the same computations
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


<img src = "https://camo.githubusercontent.com/3a0725a7d13374bb374fd3cf73ff85bd6945cfe4/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d68757a616966616465762f6d6c5f7a65726f5f746f5f6865726f2f6d61737465722f62726f6164636173742e706e673f746f6b656e3d414d534753513759534d4b46545a34593446545534494b373259483243">
Here is the same operation without broadcasting:

In [44]:
x_stretch = tf.constant([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

y_stretch = tf.constant([[1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [1, 2, 3, 4]])

print(x_stretch * y_stretch)  # Again, operator overloading

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


Most of the time, broadcasting is both time and space efficient, as the broadcast operation never materializes the expanded tensors in memory.

You see what broadcasting looks like using tf.broadcast_to.

In [45]:
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


Unlike a mathematical op, for example, broadcast_to does nothing special to save memory. Here, you are materializing the tensor.