<a href="https://colab.research.google.com/github/amazingashis/Machine_Learning_Advanced/blob/main/2_Introduction_to_Tensor_Flow_2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to Tensorflow**

<img src = "https://camo.githubusercontent.com/127d2d82f76ed9d98414011fd743b58e7c094ce4/68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f313032352f312a7657734978594733456b5237435f6c737a69715046512e706e67"/>

# **What is Tensor?**
A tensor is an N-dimensional array of data

<img src = "https://camo.githubusercontent.com/7b892ce75089d13d7a55a9e3ba037171cd9a1e99/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d68757a616966616465762f6d6c5f7a65726f5f746f5f6865726f2f6d61737465722f74656e736f722e706e673f746f6b656e3d414d534753515a445a5a4f4732484e4c4b4d5837534753373258345134"/>


# **Components of TensorFlow: Tensors and Variables**



In [1]:
import tensorflow as tf

print(tf.__version__)

2.3.0


In [2]:
import numpy as np
print(np.__version__)

1.18.5


In [4]:
x = tf.constant([[3,5,7],[4,6,8]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 7],
       [4, 6, 8]], dtype=int32)>

In [5]:
y = x[:,1]
y

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>

In [6]:
y = tf.reshape(x,[3,2])
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [7, 4],
       [6, 8]], dtype=int32)>

In [7]:
#Here is a "scalar" or "rank-0" tensor . A scalar contains a single value, and no "axes".
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
rank_1_tensor = tf.constant([2.0,3.0,4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [9]:
rank_2_sensor = tf.constant([[1,2],[3,4],[5,6]])
print(rank_2_sensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


<img src = "https://camo.githubusercontent.com/a27c59b02b8c3aa85b1b48b2c35af7500ad2660c/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d68757a616966616465762f6d6c5f7a65726f5f746f5f6865726f2f6d61737465722f74656e732e706e673f746f6b656e3d414d53475351334633374d554b56324f535a5957354c32373259424749"/>

In [10]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
                    
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


<img src = "https://camo.githubusercontent.com/41417d186a7bbd3587f5992e1163c0eeb4290efe/68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6d68757a616966616465762f6d6c5f7a65726f5f746f5f6865726f2f6d61737465722f336178697374656e736f722e706e673f746f6b656e3d414d5347535137575958575754485a4c5a364841324e53373259425232"/>

**you can convert a tensor to a NumPy array either using np.array or the tensor.numpy method:**

In [11]:
np.array(rank_2_sensor)

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [12]:
rank_2_sensor.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>>

**We can do basic math on tensors, including addition, element-wise multiplication, and matrix multiplication**

In [13]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a,b),"\n")

print(tf.multiply(a,b),"\n")

print(tf.matmul(a,b),"\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [14]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



**Tensors are used in all kinds of operations (ops).**

In [15]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

#Find the largest values
print(tf.reduce_max(c))

#Find the index of largest value

print(tf.math.argmax(c))

#Compute the Softmax
tf.nn.softmax(c)

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105860e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>


# **About Shapes**
Tensors have shapes. Some vocabulary:


* Shape: The length (number of elements) of each of the dimensions of a tensor.
* Rank: Number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
* Axis or Dimension: A particular dimension of a tensor.
* Size: The total number of items in the tensor, the product shape vector


Note: Although you may see reference to a "tensor of two dimensions", a rank-2 tensor does not usually describe a 2D space.

Tensors and tf.TensorShape objects have convenient properties for accessing these:

